import type { ToolSummary } from './contracts';

const inputHints: Record<string, string> = {
  'arcade.web.downloader': 'Paste a public media URL',
  'arcade.web.file-downloader': 'https://example.com/file.zip',
  'arcade.web.snapshot': 'https://example.com/article',
  'arcade.web.markdown': 'https://example.com/article',
  'arcade.barcode.qr-generate': 'https://example.com or plain text',
  'arcade.barcode.barcode-generate': 'Enter a number or short code',
  'arcade.barcode.batch': 'Paste one value per line',
  'arcade.text.diff': 'Paste text here; separate sides with --- RIGHT ---',
  'arcade.text.case': 'Paste text to change its case',
  'arcade.text.markdown': 'Paste Markdown to preview or export',
  'arcade.text.statistics': 'Paste text to analyze',
  'arcade.developer.regex': 'Paste text to test against the pattern',
  'arcade.developer.url': 'https://example.com/path?name=value',
  'arcade.developer.jwt': 'Paste a JWT token',
  'arcade.developer.cron': '0 9 * * 1-5',
  'arcade.network.rdap': 'example.com or 1.1.1.1',
  'arcade.convert.calculator': '(12 + 8) * 1.2',
  'arcade.convert.units': 'Set the amount and units below',
  'arcade.convert.currency': 'Set the amount and currencies below',
  'arcade.convert.time-zone': '2026-10-02T09:00:00Z',
  'arcade.convert.date-duration': '2026-10-02, or a Unix timestamp like 1735689600',
  'arcade.system.process': 'Search by process name or PID',
  'arcade.developer.hash': 'Paste text, or switch to File',
  'arcade.developer.encoding': 'Paste text, or switch to File',
  'arcade.network.site-check': 'example.com or https://example.com',
  'arcade.text.clean': 'Paste text or a list, one item per line',
  'arcade.text.structured': 'Paste JSON, YAML, TOML, or XML',
  'arcade.convert.color': '#3b82f6, rgb(59 130 246), or hsl(217 91% 60%)',
  'arcade.utility.emoji': 'Search: heart, smile, fire…',
  'arcade.web.transcript': 'Paste a YouTube or other video URL',
  'arcade.web.thumbnail': 'Paste a YouTube or other video URL',
  'arcade.web.images': 'https://example.com/gallery',
  'arcade.audio.text-to-speech': 'Type or paste the text to read aloud',
  'arcade.utility.random': 'Names or options, one per line (empty for numbers, dice, coin)',
};

const runLabels: Record<string, string> = {
  'arcade.pdf.merge': 'Merge PDFs',
  'arcade.pdf.split': 'Extract PDF pages',
  'arcade.pdf.organize': 'Organize PDF pages',
  'arcade.pdf.compress': 'Optimize PDF',
  'arcade.pdf.images-to-pdf': 'Create PDF',
  'arcade.pdf.pdf-to-images': 'Export images',
  'arcade.pdf.ocr': 'Make PDF searchable',
  'arcade.pdf.extract': 'Extract PDF content',
  'arcade.pdf.watermark': 'Add mark to PDF',
  'arcade.pdf.protect': 'Protect PDF',
  'arcade.pdf.convert': 'Convert to PDF',
  'arcade.image.convert': 'Convert image',
  'arcade.image.resize': 'Resize image',
  'arcade.image.crop': 'Edit image',
  'arcade.image.compress': 'Compress image',
  'arcade.image.background-remove': 'Remove background',
  'arcade.image.upscale': 'Enhance image',
  'arcade.image.metadata': 'Inspect image metadata',
  'arcade.image.redact': 'Redact image',
  'arcade.image.palette': 'Extract colors',
  'arcade.image.compare': 'Compare images',
  'arcade.image.ocr': 'Read image text',
  'arcade.video.convert': 'Convert video',
  'arcade.video.trim': 'Trim video',
  'arcade.video.crop': 'Edit video',
  'arcade.video.compress': 'Compress video',
  'arcade.video.join': 'Join videos',
  'arcade.video.extract-audio': 'Extract audio',
  'arcade.video.gif': 'Create animation',
  'arcade.video.frames': 'Extract frames',
  'arcade.video.inspect': 'Inspect media',
  'arcade.video.subtitles': 'Process subtitles',
  'arcade.audio.convert': 'Convert audio',
  'arcade.audio.trim': 'Trim audio',
  'arcade.audio.join': 'Join audio',
  'arcade.audio.normalize': 'Normalize loudness',
  'arcade.audio.speed-pitch': 'Change speed or pitch',
  'arcade.audio.silence': 'Trim silence',
  'arcade.audio.metadata': 'Show audio tags',
  'arcade.web.downloader': 'Download media',
  'arcade.web.file-downloader': 'Download file',
  'arcade.web.snapshot': 'Save page',
  'arcade.web.markdown': 'Extract text',
  'arcade.screen.screenshot': 'Capture screen',
  'arcade.screen.recorder': 'Start recording',
  'arcade.screen.ocr': 'Capture and read text',
  'arcade.screen.qr': 'Scan screen',
  'arcade.screen.color': 'Pick screen color',
  'arcade.screen.ruler': 'Measure screen',
  'arcade.screen.pin': 'Pin screen capture',
  'arcade.barcode.qr-generate': 'Generate QR code',
  'arcade.barcode.barcode-generate': 'Generate barcode',
  'arcade.barcode.decode': 'Read barcode',
  'arcade.barcode.batch': 'Generate labels',
  'arcade.text.diff': 'Compare text',
  'arcade.text.case': 'Change text case',
  'arcade.text.csv': 'Process table',
  'arcade.text.markdown': 'Export HTML',
  'arcade.text.statistics': 'Analyze text',
  'arcade.developer.regex': 'Test regular expression',
  'arcade.developer.encoding': 'Encode data',
  'arcade.developer.url': 'Inspect URL',
  'arcade.developer.hash': 'Calculate hash',
  'arcade.developer.identifier': 'Generate identifiers',
  'arcade.developer.jwt': 'Inspect token',
  'arcade.developer.cron': 'Explain schedule',
  'arcade.files.rename': 'Preview new names',
  'arcade.files.duplicates': 'Find duplicates',
  'arcade.files.compare': 'Compare files',
  'arcade.files.sizes': 'Analyze folder',
  'arcade.network.rdap': 'Look up domain',
  'arcade.network.ip': 'Check IP addresses',
  'arcade.security.password': 'Generate password',
  'arcade.security.encrypt': 'Encrypt file',
  'arcade.convert.calculator': 'Calculate',
  'arcade.convert.units': 'Convert units',
  'arcade.convert.currency': 'Convert currency',
  'arcade.convert.time-zone': 'Convert time zones',
  'arcade.convert.date-duration': 'Calculate',
  'arcade.system.clipboard-history': 'Open clipboard history',
  'arcade.system.paste-plain': 'Paste as plain text',
  'arcade.system.window-pin': 'Toggle always on top',
  'arcade.system.process': 'Find process',
  'arcade.system.system-info': 'Show system information',
  'arcade.pdf.sign': 'Sign PDF',
  'arcade.pdf.fill': 'Fill form',
  'arcade.image.passport': 'Make passport photo',
  'arcade.image.combine': 'Combine images',
  'arcade.image.watermark': 'Add watermark',
  'arcade.image.favicon': 'Generate icons',
  'arcade.video.auto-subtitles': 'Generate subtitles',
  'arcade.audio.denoise': 'Remove noise',
  'arcade.audio.vocals': 'Separate vocals',
  'arcade.audio.transcribe': 'Transcribe',
  'arcade.audio.text-to-speech': 'Speak text',
  'arcade.web.transcript': 'Get transcript',
  'arcade.web.thumbnail': 'Download thumbnail',
  'arcade.web.images': 'Find images',
  'arcade.network.site-check': 'Check website',
  'arcade.text.clean': 'Clean text',
  'arcade.text.structured': 'Format',
  'arcade.text.lorem': 'Generate text',
  'arcade.convert.percentage': 'Calculate',
  'arcade.convert.loan': 'Calculate EMI',
  'arcade.convert.color': 'Convert colour',
  'arcade.convert.excel-csv': 'Convert spreadsheet',
  'arcade.utility.emoji': 'Search emoji',
  'arcade.utility.timer': 'Start',
  'arcade.utility.random': 'Pick',
};

const optionLabels: Record<string, { key: string; values: Record<string, string> }> = {
  'arcade.image.metadata': { key: 'action', values: { inspect: 'Inspect image metadata', sanitize: 'Remove metadata' } },
  'arcade.pdf.protect': { key: 'action', values: { protect: 'Protect PDF', unlock: 'Unlock PDF' } },
  'arcade.video.compress': { key: 'mode', values: { quality: 'Compress video', targetSize: 'Fit target size', resolution: 'Resize video' } },
  'arcade.video.frames': { key: 'mode', values: { timestamp: 'Extract frame', interval: 'Extract frames', everyFrames: 'Extract frames' } },
  'arcade.video.subtitles': { key: 'operation', values: { extract: 'Extract subtitles', convert: 'Convert subtitles', remove: 'Remove subtitles', add: 'Add subtitle track', burn: 'Burn subtitles' } },
  'arcade.audio.trim': { key: 'mode', values: { keep: 'Trim audio', remove: 'Cut out selection' } },
  'arcade.audio.normalize': { key: 'mode', values: { loudness: 'Normalize loudness', peak: 'Normalize peaks' } },
  'arcade.audio.silence': { key: 'operation', values: { trim: 'Trim silence', shorten: 'Shorten pauses', split: 'Split at silence' } },
  'arcade.audio.metadata': { key: 'operation', values: { inspect: 'Show tags', edit: 'Save tags' } },
  'arcade.text.csv': { key: 'operation', values: { 'to-json': 'Export JSON', 'to-csv': 'Export CSV', 'to-tsv': 'Export TSV', inspect: 'Inspect table', sort: 'Sort rows', filter: 'Filter rows', deduplicate: 'Remove duplicate rows', 'select-columns': 'Select columns', 'rename-columns': 'Rename columns' } },
  'arcade.text.diff': { key: 'operation', values: { diff: 'Compare text', merge: 'Merge text' } },
  'arcade.text.case': { key: 'mode', values: { upper: 'Make UPPERCASE', lower: 'Make lowercase', title: 'Make Title Case', sentence: 'Make Sentence case', camel: 'Make camelCase', pascal: 'Make PascalCase', snake: 'Make snake_case', kebab: 'Make kebab-case', constant: 'Make CONSTANT_CASE' } },
  'arcade.developer.encoding': { key: 'action', values: { encode: 'Encode data', decode: 'Decode data' } },
  'arcade.developer.url': { key: 'action', values: { inspect: 'Inspect URL', encode: 'Encode text', decode: 'Decode text' } },
  'arcade.files.rename': { key: 'mode', values: { replace: 'Preview renamed files', regex: 'Preview renamed files', number: 'Preview numbered files', prefix: 'Preview renamed files', suffix: 'Preview renamed files', lowercase: 'Preview renamed files', uppercase: 'Preview renamed files' } },
  'arcade.security.encrypt': { key: 'action', values: { encrypt: 'Encrypt file', decrypt: 'Decrypt file' } },
  'arcade.security.password': { key: 'mode', values: { password: 'Generate password', passphrase: 'Generate passphrase', pin: 'Generate PIN', check: 'Check strength' } },
  'arcade.convert.date-duration': { key: 'action', values: { difference: 'Find difference', add: 'Add time', subtract: 'Subtract time', timestamp: 'Convert timestamp' } },
  'arcade.text.structured': { key: 'to', values: { same: 'Format', json: 'Convert to JSON', yaml: 'Convert to YAML', toml: 'Convert to TOML', xml: 'Convert to XML' } },
  'arcade.image.redact': { key: 'action', values: { redact: 'Redact image', find: 'Find personal info' } },
  'arcade.pdf.compress': { key: 'mode', values: { targetSize: 'Compress to size', lossless: 'Optimize PDF', balanced: 'Compress PDF', small: 'Compress PDF', custom: 'Compress PDF' } },
  'arcade.pdf.fill': { key: 'action', values: { list: 'List form fields', fill: 'Fill form' } },
  'arcade.image.compress': { key: 'mode', values: { targetSize: 'Compress to size', quality: 'Compress image' } },
  'arcade.audio.transcribe': { key: 'task', values: { transcribe: 'Transcribe', translate: 'Translate to English' } },
  'arcade.web.snapshot': { key: 'output', values: { pdf: 'Save as PDF', png: 'Take screenshot', jpg: 'Take screenshot' } },
  'arcade.utility.random': { key: 'mode', values: { pick: 'Pick', shuffle: 'Shuffle', teams: 'Make teams', number: 'Generate numbers', dice: 'Roll dice', coin: 'Flip coin' } },
};

export function inputPlaceholder(tool: ToolSummary, _options: Record<string, unknown> = {}): string {
  return inputHints[tool.id] ?? (tool.ui?.input.kind === 'url' ? 'https://example.com' : tool.ui?.input.kind === 'text' ? 'Enter a value' : '');
}

export function runLabel(tool: ToolSummary, options: Record<string, unknown> = {}): string {
  const dynamic = optionLabels[tool.id];
  const selected = dynamic ? String(options[dynamic.key] ?? '') : '';
  return (dynamic && dynamic.values[selected]) || runLabels[tool.id] || `Run ${tool.name}`;
}
