//! Helpers shared by every first-party executor: reading request options,
//! cancellation, building results, reading text or granted-file input, and
//! publishing generated bytes. Executors use these instead of local copies.

use crate::{Arcade, artifacts::validate_portable_filename};
use arcade_contract::{ResultStatus, ToolManifest, ToolRequest, ToolResult, ToolValue, ValueKind};
use serde_json::Value;
use std::{
    io::{Read, Write},
    sync::atomic::{AtomicBool, Ordering},
};

pub(crate) fn option_str<'a>(request: &'a ToolRequest, key: &str, default: &'a str) -> &'a str {
    request
        .options
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or(default)
}

pub(crate) fn option_bool(request: &ToolRequest, key: &str, default: bool) -> bool {
    request
        .options
        .get(key)
        .and_then(Value::as_bool)
        .unwrap_or(default)
}

/// A numeric option sent either as a JSON number or as numeric text.
pub(crate) fn option_f64(request: &ToolRequest, key: &str) -> Option<f64> {
    match request.options.get(key)? {
        Value::Number(number) => number.as_f64(),
        Value::String(text) if !text.trim().is_empty() => text.trim().parse().ok(),
        _ => None,
    }
    .filter(|value: &f64| value.is_finite())
}

/// A required number inside an inclusive range, with a readable error.
pub(crate) fn number_in(
    request: &ToolRequest,
    key: &str,
    label: &str,
    default: Option<f64>,
    range: std::ops::RangeInclusive<f64>,
) -> Result<f64, String> {
    let value = match request.options.get(key) {
        None | Some(Value::Null) => default,
        Some(Value::String(text)) if text.trim().is_empty() => default,
        Some(_) => {
            Some(option_f64(request, key).ok_or_else(|| format!("{label} must be a number"))?)
        }
    }
    .ok_or_else(|| format!("Enter {label}"))?;
    if range.contains(&value) {
        Ok(value)
    } else {
        Err(format!(
            "{label} must be between {} and {}",
            range.start(),
            range.end()
        ))
    }
}

pub(crate) fn check_cancelled(cancelled: &AtomicBool) -> Result<(), String> {
    if cancelled.load(Ordering::Acquire) {
        Err("Operation cancelled".into())
    } else {
        Ok(())
    }
}

pub(crate) fn success(
    manifest: &ToolManifest,
    outputs: Vec<ToolValue>,
    message: Option<String>,
    warnings: Vec<String>,
) -> ToolResult {
    ToolResult {
        tool_id: manifest.id.clone(),
        status: ResultStatus::Success,
        outputs,
        message,
        warnings,
        metadata: Default::default(),
    }
}

pub(crate) fn text_result(manifest: &ToolManifest, value: String, mime: &str) -> ToolResult {
    success(manifest, vec![ToolValue::text(value, mime)], None, vec![])
}

pub(crate) fn json_result(manifest: &ToolManifest, value: Value, mime: &str) -> ToolResult {
    text_result(manifest, value.to_string(), mime)
}

/// The single text value of a request (text or URL input), trimmed of nothing.
pub(crate) fn single_value(request: &ToolRequest, limit: usize) -> Result<&str, String> {
    match request.inputs.as_slice() {
        [input] if input.value.len() <= limit => Ok(&input.value),
        [_] => Err(format!("Input exceeds the {limit}-byte limit")),
        [] => Ok(""),
        _ => Err("Provide one input value".into()),
    }
}

/// The single text input of a request, read from a granted file when needed.
pub(crate) fn single_text(
    request: &ToolRequest,
    runtime: &Arcade,
    limit: usize,
    cancelled: &AtomicBool,
) -> Result<String, String> {
    let [input] = request.inputs.as_slice() else {
        return Err("This tool needs one input".into());
    };
    input_text(input, runtime, limit, cancelled)
}

/// UTF-8 text of a text value or a user-selected file, bounded by `limit`.
pub(crate) fn input_text(
    input: &ToolValue,
    runtime: &Arcade,
    limit: usize,
    cancelled: &AtomicBool,
) -> Result<String, String> {
    let bytes = input_bytes(input, runtime, limit, cancelled)?;
    String::from_utf8(bytes).map_err(|_| "Selected input is not valid UTF-8 text".into())
}

/// Bytes of a text value or a user-selected file, bounded by `limit`.
pub(crate) fn input_bytes(
    input: &ToolValue,
    runtime: &Arcade,
    limit: usize,
    cancelled: &AtomicBool,
) -> Result<Vec<u8>, String> {
    match input.kind {
        ValueKind::Text | ValueKind::Url => {
            if input.value.len() > limit {
                return Err(format!("Input exceeds the {limit}-byte limit"));
            }
            Ok(input.value.as_bytes().to_vec())
        }
        ValueKind::Artifact | ValueKind::File => {
            let file = runtime
                .grants()
                .open_scoped(&input.value)
                .map_err(|error| error.to_string())?;
            read_limited(file, limit, cancelled)
        }
    }
}

pub(crate) fn read_limited(
    mut reader: impl Read,
    limit: usize,
    cancelled: &AtomicBool,
) -> Result<Vec<u8>, String> {
    let mut bytes = Vec::new();
    let mut chunk = [0u8; 64 * 1024];
    loop {
        check_cancelled(cancelled)?;
        let count = reader.read(&mut chunk).map_err(|error| error.to_string())?;
        if count == 0 {
            return Ok(bytes);
        }
        if bytes.len().saturating_add(count) > limit {
            return Err(format!("Input exceeds the {limit}-byte limit"));
        }
        bytes.extend_from_slice(&chunk[..count]);
    }
}

/// The optional `destinationGrant` folder token of a request.
pub(crate) fn destination_grant(request: &ToolRequest) -> Result<Option<&str>, String> {
    match request.options.get("destinationGrant") {
        None | Some(Value::Null) => Ok(None),
        Some(Value::String(value)) if value.trim().is_empty() => Ok(None),
        Some(Value::String(value)) if value.len() <= 128 => Ok(Some(value)),
        Some(_) => Err("Select a valid output folder or leave Save to empty".into()),
    }
}

/// The requested `outputName`, or `fallback`, validated as a portable name.
pub(crate) fn output_name(request: &ToolRequest, fallback: &str) -> Result<String, String> {
    let name = match option_str(request, "outputName", "").trim() {
        "" => fallback,
        name => name,
    };
    validate_portable_filename(name)?;
    Ok(name.to_owned())
}

/// Stage `bytes` privately and publish them as a new, never-overwriting file.
pub(crate) fn publish_bytes(
    request: &ToolRequest,
    runtime: &Arcade,
    bytes: &[u8],
    name: &str,
    cancelled: &AtomicBool,
) -> Result<ToolValue, String> {
    check_cancelled(cancelled)?;
    validate_portable_filename(name)?;
    let staged = tempfile::NamedTempFile::new_in(runtime.artifact_staging_root())
        .map_err(|error| error.to_string())?;
    let mut file = staged.reopen().map_err(|error| error.to_string())?;
    file.write_all(bytes).map_err(|error| error.to_string())?;
    file.sync_all().map_err(|error| error.to_string())?;
    publish_file(request, runtime, staged.path(), name, cancelled)
}

/// Publish a finished file from private staging as a new, never-overwriting
/// output in the requested folder (or Arcade Box artifacts).
pub(crate) fn publish_file(
    request: &ToolRequest,
    runtime: &Arcade,
    staged: &std::path::Path,
    name: &str,
    cancelled: &AtomicBool,
) -> Result<ToolValue, String> {
    runtime
        .publish_staged_output(destination_grant(request)?, staged, name, cancelled)
        .map(|file| file.as_tool_value())
        .map_err(|error| error.to_string())
}

/// Bounded, lossy text of a child process's stderr for error messages.
pub(crate) fn stderr_excerpt(stderr: &[u8]) -> String {
    let text = String::from_utf8_lossy(stderr);
    let trimmed = text.trim();
    let start = trimmed.len().saturating_sub(1200);
    let start = (start..=trimmed.len())
        .find(|index| trimmed.is_char_boundary(*index))
        .unwrap_or(trimmed.len());
    trimmed[start..].to_owned()
}

/// A file stem that is safe to reuse in an output name, or `fallback`.
pub(crate) fn safe_stem(path: &std::path::Path, fallback: &str) -> String {
    let raw = path.file_stem().unwrap_or_default().to_string_lossy();
    let stem = raw
        .chars()
        .take(100)
        .map(|ch| {
            if ch.is_control() || matches!(ch, '/' | '\\' | '<' | '>' | ':' | '"' | '|' | '?' | '*')
            {
                '_'
            } else {
                ch
            }
        })
        .collect::<String>();
    match stem.trim_matches([' ', '.']) {
        "" => fallback.to_owned(),
        stem => stem.to_owned(),
    }
}

/// The safe stem of a granted input file, for naming outputs after it.
pub(crate) fn input_stem(runtime: &Arcade, input: &ToolValue, fallback: &str) -> String {
    match input.kind {
        ValueKind::Artifact | ValueKind::File => runtime
            .grants()
            .resolve(&input.value)
            .map(|path| safe_stem(&path, fallback))
            .unwrap_or_else(|_| fallback.to_owned()),
        ValueKind::Text | ValueKind::Url => fallback.to_owned(),
    }
}
